### PR TITLE
Add `git graph` alias to the setup instructions.

### PR DESCRIPTION
**Pull request by rkdarst**
- It would be reasonable to not have it here and introduce it only
  when needed.  On the other hand, having a single place that gets
  everyone to the required configuration we need is good (a new
  student just needs to look at these instructions).  I don't know
  what the goal is, so this PR needs discussion...

### CODE REVIEW

**Comment by wikfeldt** [comment]
sorry this was forgotten! I think it's maybe better to introduce the alias only when it's needed. For one it avoids duplication, secondly maybe it looks confusing in this lesson without further explanation

**Comment by bast** [comment]
I also think it works quite well when we introduce it during the lesson.

**Comment by rkdarst** [comment]
I wrote a long thing debating if it should be here, but in the end maybe not.  But, I think the alias should be in the setup instructions somewhere, not just in the lesson.  It's such an important alias, and I would rather not have someone miss it and we have to have the person go dig into the lesson to find it (e.g. what if they miss the first day?).

For example https://coderefinery.github.io/installation/git/#configuring-git has some stuff that's not explained there, which is slightly duplicated https://coderefinery.github.io/git-refresher/01-setup/#configuring-git.

Maybe another way to phrase the problem: "when someone says 'I don't have git graph', what's the fastest place to refer them to fix it regardless of the lessons".

Perhaps cheatsheets for the lessons?

**Comment by bast** [comment]
Good point. Somebody might join for collaborative Git and might have not been there for Git intro. I think Git configuration in the install instructions is a good place. But it seems we have duplication of information for Git configuration also.

**Comment by rkdarst** [comment]
I'll close this due to inactivity.  Stuff is changing, it can be redone if it's still needed later.  It's added to the git-collaborative reference at least (but not in the lesson text itself, even though it's used there...).

**Pull request closed without merging**
